### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/cringe#1]
To absolutely nobody's surprise the name "scaffold" is already taken on everything. I'll have to come up with something better and rename it appropriately. I'm tempted to go with "fry basket" or something to go along with the fast-food theme from [heatlamp](https://github.com/heatlamp).

**Comment by etoews** [comment]
"Crutch"

**Comment by smashwilson** [comment]
> "Crutch"

[D'oh.](https://www.npmjs.com/package/crutch)

**Comment by rgbkrk** [comment]
I do own `cringe` on npm, would you like that?

**Comment by rgbkrk** [comment]
Done, added you on npmjs.com. :wink:
